---
- hosts: all
  user: vagrant
  become: True
#- hosts: all
#  sudo: yes
  vars:
    cluster_name: Test Cluster
    vagrant_ip: 192.168.10.11
    opscenter_ip: 192.168.10.13
#    seeds: 192.168.10.11
    seeds: '192.168.56.11,192.168.56.12,192.168.56.13'
#    spark_version: spark-1.4.1-bin-hadoop2.4
#    connector_jar: spark-connector-1.4.1-driver-2.1.8-1.0.0-SNAPSHOT-fat.jar

  tasks:
  - name: install htop
    apt: name=htop state=present

  roles:
    - cassandra
#    - opscenter-agent
    - opscenter
